global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:4657']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
