
services:
 mongo:
  image: mongo:6
  container_name: mongo-db
  volumes:
   - mongo_data:/data/db
  ports:
    - "27017:27017"
  networks:
   - app-network
 
 backend:
   build: 
    context: ./backend
    dockerfile: Dockerfile
   container_name: backend
   ports:
    - "5000:5000"
   depends_on:
    - mongo
   environment:
    - NODE_ENV=production
    - PORT=5000
    - MONGODB_URI=mongodb://mongo:27017/devops_db
   networks:
    - app-network

 frontend:
  build:
   context: ./frontend
   dockerfile: Dockerfile
  container_name: frontend
  ports:
   - "80:80"
  depends_on:
   - backend
  networks:
   - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge

   
  