version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  backend:
    image: 769566606602.dkr.ecr.ap-south-1.amazonaws.com/devops-backend
    container_name: backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/devops_db
      - PORT=4657
    depends_on:
      - mongo
    ports:
      - "4657:4657"

  frontend:
    image: 769566606602.dkr.ecr.ap-south-1.amazonaws.com/devops-frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring

volumes:
  grafana-storage:

networks:
  monitoring:
